---

- name: Install and configure services
  hosts: all
  become: true
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Installing Prerequisites for Kubernetes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - vim
          - software-properties-common
        state: present


    - name: Add Google official GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present


    - name: Add Kubernetes Repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
        state: present
        filename: kubernetes
        mode: 0600


    - name: install kubelet
      apt:
        name: kubelet
        state: present
        update_cache: true

    - name: install kubeadm
      apt:
        name: kubeadm
        state: present

    - name: install kubectl
      apt:
        name: kubectl
        state: present
        force: yes

    - name: Enable service kubelet, and enable persistently
      service:
        name: kubelet
        enabled: yes

    - name: Install MongoDB
      apt:
        name: mongodb
        state: present

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Install Minio
      apt:
        name: minio
        state: present

    - name: Install NFS Server
      apt:
        name: nfs-kernel-server
        state: present

    - name: Add Keycloak apt key
      apt_key:
        url: https://keycloak.org/downloads/keycloak-24.0.1.zip
        state: present

    - name: Add Keycloak apt repository
      apt_repository:
        repo: deb https://downloads.jboss.org/keycloak/24.0.1/keycloak-24.0.1.zip
        state: present

    - name: Install Keycloak
      apt:
        name: keycloak
